### ISSUE TITLE
Unclear Installation Instructions?

### ISSUE THREAD

**Issue by haniawni** [xfleckx/LSL4Unity#1]
Hello!
Thank you very much for making this! I'm seeking to do simple BCI stuff like your classic SSVEPSpeller using Unity/LSL/BCILAB, so this perfectly suits my needs.

However, currently it's unclear how exactly to add this toolkit to a Unity project, which is aggravated by my relative unfamiliarity with Unity. 

Where should these various files be placed relative to the project root directory in order to get them to work? Should they all go in assets? or a single folder in Library? or should some things, like scripts, go in Assets and some others go in Library?

I will be testing different configurations to see if I can just figure it out, but your advice would certainly be appreciated.

**Comment by xfleckx** [comment]
Hy, 
you're welcome,
The LSL4Unity Project should be checked out to the Asset directory of your project. 
I will update the Installation instructions tonight... stay calm :+1:

**Comment by haniawni** [comment]
Cool! Thank you very much for the help!
Once I put the entire repo in my Assets/LSL4Unity folder and follow along with the example, "FindObjectOfType<LSLMarkerStream>()" seems unable to find the LSLMarkerStream script, instead returning null. I'm attempting to figure out exactly why that is.

Additionally, It seems necessary to additionally add a "using Assets.LSL4Unity.Scripts;" line in the script that uses the LSLMarkerStream for the editor to be able to know what an LSLMarkerStream is.

Lastly, do I need to do something to make thee LSLMarkerStream script actually run? For example, adding it to the camera as a component or something so that it actually does get instantiated?

**Comment by xfleckx** [comment]
You need to put the LSLMarkerStream Script onto any GameObject. I recommend using a dedicated GameObject top level in the scene hierarchy. If this is done, the FindObjectOfType<LSLMarkerStream> call can do it's job. I will put a prefab implementing this in the package.

You're right regarding the required namespace, I missed that in the example.

Yes each Script derived from MonoBehaviour must be instantiated through dragging it to a GameObject or using  `anyGameObjectReference.AddComponent<LSLMarkerStream>()` somewhere in your code.

**Comment by haniawni** [comment]
Hey,
Perfect, the documentation is 100% clear and easy to follow now. There's one miniscule thing I reference in the pull request https://github.com/xfleckx/LSL4Unity/pull/3 that may be worth considering, but thank you very, very much for the help on this, especially for being so quick to reply!

Thanks!

**Comment by xfleckx** [comment]
Thanks for the Hint... I added it to the Docs. Maybe I should make this the default name, but I'm not sure about this.
