### ISSUE TITLE
Can't have multiple streams coming from outside to Unity.

### ISSUE THREAD

**Issue by AntoineOmind** [xfleckx/LSL4Unity#11]
Hi, I work at **Open Mind Innovation** and I'm using **LSL4Unity** to recieve and send data with Unity.

**My problem:**
It seems that I can have multiple streams coming from outside to Unity. 
It only use one of the multiple streams.

**Programs:**
- OpenVibes _(with LSL Export)_
- Unity 5.5.

We would be happy to stay in contact with you throughout our project.
You can reach me at: antoine@omind.me

**Comment by xfleckx** [comment]
Hy Antoine,

I will take a look at your problem. :) 

First question, how did you try to access the streams? I recommend to use exact one script per inlet aka stream. Did you follow the following the [example](https://github.com/xfleckx/LSL4Unity/wiki/Process-Incoming-Streams)? You need to implement a script for each stream you want to receive.

Could you provide more informations?

kind regards
Markus

**Comment by AntoineOmind** [comment]
First I setup OpenVibe with 2 LSL Export with different streams and marker names and I run the streams.

Then I tried multiple things:
- Having 2 objects with a TransformMapping.cs on each with the respective names of the streams
- Same with 2 objects with ExampleFloatInlet.cs
- And even having a TransformMapping.cs on one object and a ExampleFloatInlet.cs on another

But each time, I see the output of only one of the 2 incoming streams.

_PS: I don't know if it's an helpfull info, but reading a stream while sending another one is working._

**Comment by xfleckx** [comment]
ok I will try to reproduce the problem!

**Comment by xfleckx** [comment]
Hy, 

regarding to some strange thing with the ContinousResolver, I added a new implementation which uses just one Resolver in the current Scene and utilizes UnityEvents to initialize your actual stream... Update LSL4Unity to the [latest version](https://github.com/xfleckx/LSL4Unity/commit/09355093ccdd9e78076833dd2fa82f4af4fde84b) and see the [updated documentation](https://github.com/xfleckx/LSL4Unity/wiki/Process-Incoming-Streams). 

Please let me know if something is not easy to understand or does not behave as expected.... I'm sorry but still not sure what design for implementation works best...

**Comment by AntoineOmind** [comment]
It works perfectly, I've been able to have multiple incoming streams.

Thank you so much, you're awesome! 🥇

**Comment by xfleckx** [comment]
Glad that I could help 😊 

Thanks for using and contributing! I will close this issue...
