### ISSUE TITLE
Several streams appear combined when using with OpenBCI

### ISSUE THREAD

**Issue by mariusrubo** [xfleckx/LSL4Unity#18]
Hello (again), 

First of all thanks for making this great project! 
I'm not sure if this is the right place to ask this question, but maybe you can give me directions. I'm streaming data from OpenBCI into Unity using LSL4Unity. I catch the stream using your Resolver.cs and your "protected override void Process(float[] newSample, double timeStamp)" function. When I simply note down all numbers streaming in "newSample[0]" and plot them, I get the attached image. The voltage changes almost instantly as I let the electrodes touch (that's good), but it seems like there are several signals combinded into one. Can you make sense of this plot?
![plot_newsample 0](https://user-images.githubusercontent.com/24437119/30056520-502cad0e-9233-11e7-9e57-fbb48ae35383.jpeg)

Best, 
Marius

**Comment by mariusrubo** [comment]
Maybe zooming in on this plot shows more clearly how the values jump.
![plot_newsample 0 zoom](https://user-images.githubusercontent.com/24437119/30056688-f69a2f86-9233-11e7-9376-137851714c0d.jpeg)

**Comment by cboulay** [comment]
That looks like a multiplexed signal. Do you have 5 channels?
What is the length of newSample on every call to Process?

I don't use C# very much, but here are a few things that come to mind:

* Your print function is treating newSample[0] as a pointer to an array and is printing everything in the array
    * This is very much language-specific so I might be way off base.
* Whatever is filling your stream is doing so incorrectly. i.e., it is filling a 6-channel stream with 5 channels of data.
* The LSL packet structure has changed between the version used by the program pushing samples and the version used by Unity.
    * This seems unlikely because, as far as I know, the LSL packet structure has not changed in a long time.

**Comment by mariusrubo** [comment]
Thanks for your response! I have 8 channels, and Unity confirms that (using newSample.Length). Plotting all of these 8 channels side-by-side while measuring nothing (except channel one was placed near my heart, thus the spikes) shows a similar pattern in all channels: 
![plot_newsample_c](https://user-images.githubusercontent.com/24437119/30103537-3c9b6bc0-92f3-11e7-92a7-f83c9fdebb92.jpeg)

Observing the data stream in OpenBCI's GUI looks normal:

![plot_newsample_openbci](https://user-images.githubusercontent.com/24437119/30103579-56e301a0-92f3-11e7-9e91-2a95144a402b.jpg)

**Comment by xfleckx** [comment]
Hy, 

Unfortunately, I'm on holiday and don't have access to a notebook for testing purposes and further investigations... 

Could you show us the code which writes the data somewhere and also the plotting script... 

I won't expect a bug in the implementation, maybe there ist a speed issue between the rate data is produced and consumed... so you got multiple values for one timepoint in the plot... just a thought...

**Comment by mariusrubo** [comment]
My code is really simple. In Unity, I note down all newSample[] values in a .csv file as they come in. 

```
void Start()
        {
            string path = "C:/Users/mar39lw/Documents/Projects/2017_Open_Hardware/openbci_data.csv";
            sw = new StreamWriter(path);
        }

protected override void Process(float[] newSample, double timeStamp)
        {
            s1 = newSample[0];
            s2 = newSample[1];
            s3 = newSample[2];
            s4 = newSample[3];
            s5 = newSample[4];
            s6 = newSample[5];
            s7 = newSample[6];
            s8 = newSample[7];
            
            Text = s1.ToString() + ";" + s2.ToString() + ";" + s3.ToString() + ";" + s4.ToString() + ";" + s5.ToString() + ";" + s6.ToString() + ";" + s7.ToString() + ";" + s8.ToString();
            sw.WriteLine(Text);
        }
```


Then in R, I read the .csv-file and plot the values. 

```
rm(list = ls())
path <- "C:/Users/mar39lw/Documents/Projects/2017_Open_Hardware/openbci_data.csv"
data <- read.csv(file = path, header = F, sep = ";", quote = "\"", dec = ",", stringsAsFactors=FALSE)
names(data) <- c("channel1", "channel2", "channel3", "channel4", "channel5", "channel6", "channel7", "channel8")

data$channel1 <- as.numeric(as.character(data$channel1))
data$channel2 <- as.numeric(as.character(data$channel2))
data$channel3 <- as.numeric(as.character(data$channel3))
data$channel4 <- as.numeric(as.character(data$channel4))
data$channel5 <- as.numeric(as.character(data$channel5))
data$channel6 <- as.numeric(as.character(data$channel6))
data$channel7 <- as.numeric(as.character(data$channel7))
data$channel8 <- as.numeric(as.character(data$channel8))

par(mfrow=c(4,2))
start <- 2000
end <- 2800
plot(data$channel1[start:end])
plot(data$channel2[start:end])
plot(data$channel3[start:end])
plot(data$channel4[start:end])
plot(data$channel5[start:end])
plot(data$channel6[start:end])
plot(data$channel7[start:end])
plot(data$channel8[start:end])
`

**Comment by mariusrubo** [comment]
If I plot the LSL timestamp against the Unity frame, you can see that it is not always the same number of chunks that come in per frame, but the number varies between 3 and 5. As far as I understand this, it should however not be a problem at all?

![plot_timestamp_frame](https://user-images.githubusercontent.com/24437119/30105991-781eadf4-92fa-11e7-9120-555daab66b38.jpeg)

**Comment by xfleckx** [comment]
Hm, could you check the result of 

data$channel1 <- as.numeric(as.character(data$channel1))
I would expect that "data$channel1" contains a vector of vectors instead an vector of single numerical values

**Comment by mariusrubo** [comment]
That doesn't seem to be the problem: the values in data$channel1 don't change when I turn them into numerics. 
data$channel1 simply lists all values that came in through newSample[0].

**Comment by xfleckx** [comment]
I'm still not sure... could you provide a  head of the csv file (the first n Lines) maybe 5 lines...

Another:

Your are not saving the timestamps from lsl, you just count the samples when plotting... could you change the code for writing the csv file so that you write the timestamp for each sample to the first column?

Don't get me wrong, I don't want to say that your code ist wrong but I guess their is a strange thing somewhere between the process of reading the samples (which happens multiple times per unity (update) frame as expected) and transforming them into the plot... since lastSample[0] is always just one float value! In C# your working on safe types not on bare memory where you could try to read continuously on a memory address to unleash all evil...

**Comment by mariusrubo** [comment]
Actually I do take the timestamps, I just excluded that part of the code above to provide a minimal example. The image shows what my data looks like. The only thing that's strange is that numbers don't have the same amount of decimals.

![openbci_data](https://user-images.githubusercontent.com/24437119/30110029-e755ce4c-9308-11e7-8cc7-94476a08b4fe.jpg)

**Comment by xfleckx** [comment]
Hm, the data looks like i would it expect to... so I don't think that the problem is on the LSL side... could you upload a csv file containing a few seconds of data? Maybe as gist or as Dropbox link?

Maybe, I'm totally messed due to a experimental mixture of too much ouzo and greek coffee.. but I think we miss interpret the plot... could you try a line plot instead of point/circleplot? 

And use the openbci timestamp as x-axes...

**Comment by mariusrubo** [comment]
I think I found the mistake: While OpenBCI applies a notch filter of 50Hz in its GUI, data is sent in its raw format over LSL. At a sampling rate of 250Hz, the plots make sense.
I'll try to confirm this idea and present a solution when I have found one, for people who run into the same beginner's mistake.
So Markus thank you very much for your help, and enjoy the ouzo ;-)

**Comment by mariusrubo** [comment]
I now apply Notch filters to the signal. For a description see https://github.com/mariusrubo/Unity-IIR-Online-Filtering

**Comment by xfleckx** [comment]
Thank you for the clarification and the example code reference!
