### ISSUE TITLE
Lacking Mac OSx Support

### ISSUE THREAD

**Issue by haniawni** [xfleckx/LSL4Unity#2]
Hello!
When running this build of the library in its current state on MacOSx, it throws an error as "pathToAllLibs" in LSL.cs line 922 has not been initialized. This seems to be because the preceding if statements only include the Windows and Linux cases. Poking around reveals that my environment has the env variables "Unity_EDITOR_OSX", "UNITY_EDITOR_64", "UNITY_STANDALONE_OSX", "UNITY_EDITOR", and "UNITY_STANDALONE".

I can probably add the necessary changes myself, but want to confirm a few things:
- DLLs are exclusively for Windows, correct? Which would imply I should be using the "liblsl64.so" file
- It seems to still request a DLL: 

> DllNotFoundException: Assets/LSL4Unity/lib/liblsl64.so
LSL.liblsl+StreamInfo..ctor (System.String name, System.String type, Int32 channel_count, Double nominal_srate, channel_format_t channel_format, System.String source_id) (at Assets/LSL4Unity/LSL.cs:133)
Assets.LSL4Unity.Scripts.LSLMarkerStream.Start () (at Assets/LSL4Unity/Scripts/LSLMarkerStream.cs:26)

How can I tell it to look for an .so file instead?

**Comment by xfleckx** [comment]
Unfortunately, I was not able to figure this out. Lacking an mac os environment, I'm not able to implement or test that by myself. But maybe we can figure this out together... 

I added the all the necessary stuff for MacOS support with the last two commits. So please get the latest version of the master branch by using 

> git pull origin master

if it won't work... please remove all changes you made within the LSL4Unity package....

if this seems to be too complicated... just remove the LSL4Unity package.. restart Unity (to unload all libraries), download or clone it again and let's see whats happening.

**Comment by haniawni** [comment]
Hello!
Your fix was almost perfect, the .bundle file is exactly what it was expecting, the one small change is that in OSX editor mode it needs to look in the /Assets/LSL4Unity/lib/ directory rather than "../Plugins"

I've sent a pull request with the change here: https://github.com/xfleckx/LSL4Unity/pull/3

**Comment by xfleckx** [comment]
I'm glad to read that! Thanks for the contribution! Let me know when you have been trying to compile your Unity app using LSL.
