### ISSUE TITLE
StreamInlet does not throw exceptions

### ISSUE THREAD

**Issue by triplem161** [xfleckx/LSL4Unity#22]
Hello, 

I'm using your version of `LSL.cs` on Windows, I decided to dive into the liblsl and wrote my own resolver. So far so good. 

But while it seems to work correctly it seems that the streamInlet is not able to throw any `LostException`. Even though I'm disconnecting the stream from the other side. 

So I'm hesitating between an issue from the dll (~~our project's dll is quite old now~~, I got the latest zip from master, same issue) or my way of coding.

This is the piece of code called every frame.

```
	        try {
			_lastSampleTimestamp = _streamInlet.pull_sample(_streamSample, 0);
		} catch (liblsl.LostException vE) {
			_streamIsAvailable = false;
			Debug.LogException(vE);
			StreamNotAvailable();
		}
```

As I read in the LSL.cs class, in the documentation, `StreamInlet.pull_sample` is supposed to throw this exception. I did log the function` check_error` but it receives 0 has well (this is why I think it must be an issue with our dll)

Any solution ? Thanks

**Comment by xfleckx** [comment]
Hy, I apologize for the late response,

Unfortunately, I got less time to work on this project... anyway... I will have a look at the problem later this day...

**Comment by triplem161** [comment]
Hey, your response is not late at all :) 

No worries, I was actually thinking about posting this issue on the main repo as well since i believe it's more an issue on their side than on the unity side.

**Comment by triplem161** [comment]
Hey, we found the issue. It was me being an idiot ....

I thought that the exception was thrown when the stream was lost, but it seems thas it thrown only if the inlet recover param was set to true. 

I set the recover param to false and i am now notified for each throw. I'll just need to do the recover on my side.

Thanks anyway :)
