### ISSUE TITLE
LSL and VRPN? 

### ISSUE THREAD

**Issue by XORGIN** [xfleckx/LSL4Unity#25]
Hi just is it possible and how? thanks

**Comment by xfleckx** [comment]
You might be able to transform a VRPN Stream to a set of LSL streams. You might face the issue of transforming a tree into a set of linear elements. Currently, LSL4Unity did not provide a feature for that.

**Comment by aalizee64** [comment]
ok thanks  so What is the another possibility?

**Comment by xfleckx** [comment]
My first thought would be writing a python script or a c++ app implementing the vrpn client and on each message recieved it would select or aggregate the data and push it as samples to an LSL stream.

**Comment by cboulay** [comment]
I don't know what your application is, but if all you want to do is get tracker pose data into LSL, and if you're using SteamVR, then you might want to look at [LSLOpenVR](https://github.com/labstreaminglayer/App-OpenVR).
