### ISSUE TITLE
pull_sample from Stream Inlet throws ArgumentError even for floats (OSX Editor)

### ISSUE THREAD

**Issue by haniawni** [xfleckx/LSL4Unity#4]
Hello again!
I'm attempting to do an SSVEP BCI using Unity and LSL, so need to be able to read input from streams as well. 
When I run the streamInlet script trying to read from, for example, the test "BioSemi" stream of random floats generated by LSL's SendData.py, however, it throws an argument error, saying:

> ArgumentException: An argument was incorrectly specified (e.g., wrong format or wrong length).
LSL.liblsl.check_error (Int32 ec) (at Assets/LSL4Unity/LSL.cs:889)
LSL.liblsl+StreamInlet.pull_sample (System.Single[] sample, Double timeout) (at Assets/LSL4Unity/LSL.cs:585)
Assets.LSL4Unity.Scripts.LSLInlet.pullSamples () (at Assets/LSL4Unity/Scripts/LSLInlet.cs:47)
Assets.LSL4Unity.Scripts.LSLInlet.FixedUpdate () (at Assets/LSL4Unity/Scripts/LSLInlet.cs:57)

My attempts to further debug this are stymied by the inaccessibility of Debug.log from the LSL.cs file.

The same error is elicited at the same line of code if you attempt to listen to a marker stream of strings instead.

Does this replicate for non-OSX users? Is there something obvious to check or try doing that I don't know of?

Thank you!

**Comment by xfleckx** [comment]
Unfortunately, this bug did not occur on the Windows platform... I will have a look tomorrow for potentially issues...

**Comment by xfleckx** [comment]
I has been adding an example implementation [commit](https://github.com/xfleckx/LSL4Unity/commit/e6120d849069e3c87cc2baa755fb20795f51082b) for float streams and some base implementations for all other types of streams... Make an pull and try the Example stream with the biosemi demo stream.

**Comment by haniawni** [comment]
Hello!
Thank you, once again, for your nigh-instantaneous turn-around time! I've updated to your new version and I love it, the structure is much more clear! In addition, it **worked right out of the box** with the LSL's SendData.py, pulling data and trivially easy to modify it to print to screen or whatever you could want with it.

I've come across a few minor changes in testing it and reading your code, expect a pull request by the end of the day with it, fixing simple stuff like cleaner debug log printing and allowing additional start()-stage child class stuff.
