### ISSUE TITLE
How to create LSL 

### ISSUE THREAD

**Issue by yangyang1018** [xfleckx/LSL4Unity#58]
Hello all.

I am trying to connect LSL to a software called MEDUSA@. It is a software used for electroencephalography (EEG) data studies.
My question is:
How can I create an LSL that is MEDUSA@ software can read the signals transmitted by my EEG measurement device in real time.

Does anyone else have this problem?

**Comment by cboulay** [comment]
Hi @yangyang1018 , this question doesn't seem to have anything to do with LSL4Unity so I am going to close it. I think the best repo for this question would be github.com/sccn/labstreaminglayer

I tried to look at the medusabci.com website but it was so slow it was unusable.
But, based on their GitHub repo, I'd expect that they already have LSL integrated. e.g.: 
https://github.com/medusabci/medusa-platform/blob/master/src/acquisition/lsl_utils.py#L79

So it would be up to you to create an inlet to view the data.

I don't think raw data is very useful in Unity. You probably want a process to pull the raw data, do signal processing, extract features, and push the features or decoded effector states to another stream.
Then your Unity app probably wants to pull this feature / state stream.

**Comment by yangyang1018** [comment]
Thank you for your response and I will seriously consider these suggestions you have mentioned!













At 2023-10-16 02:43:44, "Chadwick Boulay" ***@***.***> wrote:

Hi @yangyang1018 , this question doesn't seem to have anything to do with LSL4Unity so I am going to close it. I think the best repo for this question would be github.com/sccn/labstreaminglayer

I tried to look at the medusabci.com website but it was so slow it was unusable.
But, based on their GitHub repo, I'd expect that they already have LSL integrated. e.g.:
https://github.com/medusabci/medusa-platform/blob/master/src/acquisition/lsl_utils.py#L79

So it would be up to you to create an inlet to view the data.

I don't think raw data is very useful in Unity. You probably want a process to pull the raw data, do signal processing, extract features, and push the features or decoded effector states to another stream.
Then your Unity app probably wants to pull this feature / state stream.
