### ISSUE TITLE
Any 'more official' version in the wild?

### ISSUE THREAD

**Issue by cboulay** [xfleckx/LSL4Unity#8]
Hi Markus,

I'm sorry for posting an issue for a silly question, but I couldn't find your e-mail address.

On the [neuropype](http://neuropype.io/) website, under Hardware List, it lists compatibility with different devices/environments via LSL. Under the sub-category "Stimulation Presentation Software", Unity is in the list.

Do you happen to know if they are implying the use of this repository, or are is there another Unity-LSL plugin in the wild that you might have heard of?

P.S. I have a UE4 LSL Plugin. It's private because I can't support it and it's not quite feature-rich enough (only floats and strings), but I'll happily grant access to anyone so long as they know there is no support available.

**Comment by xfleckx** [comment]
Hy Chadwick, 

thanks for the Question - there is nothing silly on it! I guess they have their own thing going on, or implying it based on the C# interface from the LSL App. I might have missed the occurence of another implementation of LSL for Unity. But Google just shows this one...  Oh no... I double checked this.. there is another one [LSL2Unity](https://github.com/conphyture/LSL2Unity) but a way more alpha than mine. I hope we could work together - I wrote them.... let's see... 

Anyway, I tried to support this implementation as good as I can... 

Towards the UE4 - glad to hear that you are working on that. :+1: I will join you some day if necessary. After finishing my thesis which made heavy use on Unity - I would like to also learn the Unreal Engine by implementing an LSL Wrapper... - or now - contributing to yours :)

**Comment by cboulay** [comment]
OK great, thanks for the info.
I added you to the lsl-ue4 project anyway without any expectation that you'll do anything with it in the near future.

Good luck with your thesis!

**Comment by ZijingMao** [comment]
Hi Chadwick, 

I have tested LSL4Unity in the past few month and currently want to switch to UE4 to have new project of BCI using LSL, searched the internet and found you are working on that, I think that's great! I would like to contribute to UE4 LSL plugin and explore different application possibilities. But I'm new to UE4 and will try hard on that 😆  @cboulay
